use super::languages::Language;

pub(super) fn is_keyword(word: &str, lang: Language) -> bool {
    match lang {
        Language::Rust => matches!(
            word,
            "as" | "async"
                | "await"
                | "break"
                | "const"
                | "continue"
                | "crate"
                | "dyn"
                | "else"
                | "enum"
                | "extern"
                | "false"
                | "fn"
                | "for"
                | "if"
                | "impl"
                | "in"
                | "let"
                | "loop"
                | "match"
                | "mod"
                | "move"
                | "mut"
                | "pub"
                | "ref"
                | "return"
                | "self"
                | "Self"
                | "static"
                | "struct"
                | "super"
                | "trait"
                | "true"
                | "type"
                | "unsafe"
                | "use"
                | "where"
                | "while"
                | "yield"
        ),
        Language::C | Language::Cpp => matches!(
            word,
            "auto"
                | "break"
                | "case"
                | "class"
                | "const"
                | "continue"
                | "default"
                | "delete"
                | "do"
                | "else"
                | "enum"
                | "explicit"
                | "export"
                | "extern"
                | "false"
                | "for"
                | "friend"
                | "goto"
                | "if"
                | "inline"
                | "mutable"
                | "namespace"
                | "new"
                | "noexcept"
                | "nullptr"
                | "operator"
                | "override"
                | "private"
                | "protected"
                | "public"
                | "register"
                | "reinterpret_cast"
                | "return"
                | "sizeof"
                | "static"
                | "static_assert"
                | "static_cast"
                | "struct"
                | "switch"
                | "template"
                | "this"
                | "throw"
                | "true"
                | "try"
                | "typedef"
                | "typeid"
                | "typename"
                | "union"
                | "using"
                | "virtual"
                | "volatile"
                | "while"
        ),
        Language::CSharp => matches!(
            word,
            "abstract"
                | "as"
                | "async"
                | "await"
                | "base"
                | "break"
                | "case"
                | "catch"
                | "class"
                | "const"
                | "continue"
                | "default"
                | "delegate"
                | "do"
                | "else"
                | "enum"
                | "event"
                | "explicit"
                | "extern"
                | "false"
                | "finally"
                | "fixed"
                | "for"
                | "foreach"
                | "goto"
                | "if"
                | "implicit"
                | "in"
                | "interface"
                | "internal"
                | "is"
                | "lock"
                | "namespace"
                | "new"
                | "null"
                | "operator"
                | "out"
                | "override"
                | "params"
                | "private"
                | "protected"
                | "public"
                | "readonly"
                | "ref"
                | "return"
                | "sealed"
                | "sizeof"
                | "stackalloc"
                | "static"
                | "struct"
                | "switch"
                | "this"
                | "throw"
                | "true"
                | "try"
                | "typeof"
                | "unchecked"
                | "unsafe"
                | "using"
                | "virtual"
                | "void"
                | "volatile"
                | "while"
        ),
        Language::Java => matches!(
            word,
            "abstract"
                | "assert"
                | "break"
                | "case"
                | "catch"
                | "class"
                | "const"
                | "continue"
                | "default"
                | "do"
                | "else"
                | "enum"
                | "extends"
                | "final"
                | "finally"
                | "for"
                | "goto"
                | "if"
                | "implements"
                | "import"
                | "instanceof"
                | "interface"
                | "native"
                | "new"
                | "null"
                | "package"
                | "private"
                | "protected"
                | "public"
                | "return"
                | "static"
                | "strictfp"
                | "super"
                | "switch"
                | "synchronized"
                | "this"
                | "throw"
                | "throws"
                | "transient"
                | "try"
                | "void"
                | "volatile"
                | "while"
                | "true"
                | "false"
        ),
        Language::JavaScript | Language::TypeScript => matches!(
            word,
            "async"
                | "await"
                | "break"
                | "case"
                | "catch"
                | "class"
                | "const"
                | "continue"
                | "debugger"
                | "default"
                | "delete"
                | "do"
                | "else"
                | "export"
                | "extends"
                | "false"
                | "finally"
                | "for"
                | "from"
                | "function"
                | "get"
                | "if"
                | "implements"
                | "import"
                | "in"
                | "instanceof"
                | "interface"
                | "let"
                | "new"
                | "null"
                | "of"
                | "return"
                | "set"
                | "static"
                | "super"
                | "switch"
                | "this"
                | "throw"
                | "true"
                | "try"
                | "type"
                | "typeof"
                | "undefined"
                | "var"
                | "void"
                | "while"
                | "with"
                | "yield"
        ),
        Language::Go => matches!(
            word,
            "break"
                | "case"
                | "chan"
                | "const"
                | "continue"
                | "default"
                | "defer"
                | "else"
                | "fallthrough"
                | "for"
                | "func"
                | "go"
                | "goto"
                | "if"
                | "import"
                | "interface"
                | "map"
                | "package"
                | "range"
                | "return"
                | "select"
                | "struct"
                | "switch"
                | "type"
                | "var"
                | "true"
                | "false"
                | "nil"
                | "iota"
        ),
        Language::Php => matches!(
            word,
            "abstract"
                | "and"
                | "array"
                | "as"
                | "break"
                | "case"
                | "catch"
                | "class"
                | "clone"
                | "const"
                | "continue"
                | "declare"
                | "default"
                | "do"
                | "echo"
                | "else"
                | "elseif"
                | "empty"
                | "enddeclare"
                | "endfor"
                | "endforeach"
                | "endif"
                | "endswitch"
                | "endwhile"
                | "eval"
                | "exit"
                | "extends"
                | "final"
                | "finally"
                | "fn"
                | "for"
                | "foreach"
                | "function"
                | "global"
                | "goto"
                | "if"
                | "implements"
                | "include"
                | "include_once"
                | "instanceof"
                | "insteadof"
                | "interface"
                | "isset"
                | "list"
                | "match"
                | "namespace"
                | "new"
                | "or"
                | "print"
                | "private"
                | "protected"
                | "public"
                | "require"
                | "require_once"
                | "return"
                | "static"
                | "switch"
                | "throw"
                | "trait"
                | "try"
                | "use"
                | "var"
                | "while"
                | "xor"
                | "yield"
                | "true"
                | "false"
                | "null"
        ),
        Language::Python => matches!(
            word,
            "and"
                | "as"
                | "assert"
                | "async"
                | "await"
                | "break"
                | "class"
                | "continue"
                | "def"
                | "del"
                | "elif"
                | "else"
                | "except"
                | "False"
                | "finally"
                | "for"
                | "from"
                | "global"
                | "if"
                | "import"
                | "in"
                | "is"
                | "lambda"
                | "None"
                | "nonlocal"
                | "not"
                | "or"
                | "pass"
                | "raise"
                | "return"
                | "True"
                | "try"
                | "while"
                | "with"
                | "yield"
        ),
        Language::Bash => matches!(
            word,
            "case"
                | "do"
                | "done"
                | "elif"
                | "else"
                | "esac"
                | "fi"
                | "for"
                | "function"
                | "if"
                | "in"
                | "select"
                | "then"
                | "until"
                | "while"
                | "echo"
                | "exit"
                | "export"
                | "local"
                | "return"
                | "set"
                | "shift"
                | "source"
        ),
        Language::Json => matches!(word, "true" | "false" | "null"),
        _ => false,
    }
}

pub(super) fn is_builtin_type(word: &str, lang: Language) -> bool {
    match lang {
        Language::Rust => matches!(
            word,
            "bool"
                | "char"
                | "i8"
                | "i16"
                | "i32"
                | "i64"
                | "i128"
                | "isize"
                | "u8"
                | "u16"
                | "u32"
                | "u64"
                | "u128"
                | "usize"
                | "f32"
                | "f64"
                | "str"
                | "String"
                | "Option"
                | "Some"
                | "None"
                | "Result"
                | "Ok"
                | "Err"
                | "Vec"
                | "Box"
                | "Rc"
                | "Arc"
                | "Cell"
                | "RefCell"
                | "HashMap"
                | "HashSet"
        ),
        Language::C | Language::Cpp => matches!(
            word,
            "bool"
                | "char"
                | "char16_t"
                | "char32_t"
                | "wchar_t"
                | "short"
                | "int"
                | "long"
                | "signed"
                | "unsigned"
                | "float"
                | "double"
                | "void"
                | "size_t"
                | "int8_t"
                | "int16_t"
                | "int32_t"
                | "int64_t"
                | "uint8_t"
                | "uint16_t"
                | "uint32_t"
                | "uint64_t"
                | "string"
                | "vector"
                | "map"
                | "set"
                | "pair"
        ),
        Language::CSharp => matches!(
            word,
            "bool"
                | "byte"
                | "sbyte"
                | "char"
                | "decimal"
                | "double"
                | "float"
                | "int"
                | "uint"
                | "nint"
                | "nuint"
                | "long"
                | "ulong"
                | "short"
                | "ushort"
                | "object"
                | "string"
                | "dynamic"
                | "var"
        ),
        Language::Java => matches!(
            word,
            "boolean"
                | "byte"
                | "char"
                | "short"
                | "int"
                | "long"
                | "float"
                | "double"
                | "String"
                | "Integer"
                | "Boolean"
                | "Long"
                | "Double"
                | "Float"
                | "List"
                | "Map"
                | "Set"
                | "ArrayList"
                | "HashMap"
        ),
        Language::JavaScript | Language::TypeScript => matches!(
            word,
            "Array"
                | "Boolean"
                | "Date"
                | "Error"
                | "Function"
                | "JSON"
                | "Map"
                | "Math"
                | "Number"
                | "Object"
                | "Promise"
                | "RegExp"
                | "Set"
                | "String"
                | "Symbol"
                | "console"
                | "document"
                | "window"
                | "any"
                | "boolean"
                | "never"
                | "number"
                | "string"
                | "unknown"
                | "void"
        ),
        Language::Go => matches!(
            word,
            "bool"
                | "byte"
                | "complex64"
                | "complex128"
                | "error"
                | "float32"
                | "float64"
                | "int"
                | "int8"
                | "int16"
                | "int32"
                | "int64"
                | "rune"
                | "string"
                | "uint"
                | "uint8"
                | "uint16"
                | "uint32"
                | "uint64"
                | "uintptr"
        ),
        Language::Python => matches!(
            word,
            "int"
                | "float"
                | "str"
                | "bool"
                | "list"
                | "dict"
                | "set"
                | "tuple"
                | "bytes"
                | "object"
                | "type"
                | "self"
        ),
        _ => false,
    }
}
